export default {
    headers: [{
        text: 'แก้ไข / ลบ',
        align: 'center',
        sortable: false
    }, {
        text: 'รหัสประจำตัวประชาชน',
        align: 'center'
      }, {
        text: 'ยศ',
        value: 'rank',
        align: 'center'
      }, {
        text: 'ชื่อ',
        align: 'center'
      }, {
        text: 'นามสกุล',
        align: 'center'
      }, {
        text: 'เพศ',
        align: 'center'
      }, {
        text: 'วันเกิด',
        align: 'center'
      }, {
        text: 'บ้านเลขที่',
        align: 'center'
      }, {
        text: 'หมู่ที่',
        align: 'center'
      }, {
        text: 'ถนน',
        align: 'center'
      }, {
          text: 'ตำบล',
          align: 'center'
      }, {
          text: 'รหัสไปรษณีย์',
          align: 'center'
      }, {
          text: 'สัญชาติ',
          align: 'center'
      }, {
          text: 'ประเภทกำลังพล',
          align: 'center'
      }, {
          text: 'ระยะเวลาจ้าง',
          align: 'center'
      }, {
          text: 'ประเภทเงินจ้าง',
          align: 'center'
      }, {
          text: 'ประเภท ชม. สอน',
          align: 'center'
      }, {
          text: 'ตำแหน่งบริหาร',
          align: 'center'
      }, {
          text: 'ระดับตำแหน่ง',
          align: 'center'
      }, {
          text: 'ตำแหน่ง',
          align: 'center'
      }, {
          text: 'วันบรรจุ',
          align: 'center'
      }, {
          text: 'วันเริ่มทำงาน',
          align: 'center'
      }, {
          text: 'ความเชี่ยวชาญ',
          align: 'center'
      }, {
          text: 'วิชาที่สอน',
          align: 'center'
      }, {
          text: 'หมวดวิชาสอน',
          align: 'center'
      }, {
          text: 'ความพิการ',
          align: 'center'
      }, {
          text: 'ช่วงรายได้',
          align: 'center'
      }, {
          text: 'ศาสนา',
          align: 'center'
      }, {
          text: 'ประเภทการเริ่มตำแหน่ง',
          align: 'center'
      }, {
          text: 'เครื่องราชอิสริยาภรณ์',
          align: 'center'
      }, {
          text: 'วันที่ออก Passport',
          align: 'center'
      }, {
          text: 'Passport หมดอายุ',
          align: 'center'
      }, {
          text: 'สถานะ Passport',
          align: 'center'
      }]
}